SHELL := bash                                                                                                               .SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

.PHONY: zip-sources
	zip -r latex-sources.zip causal_decision_making.tex causal_decision_making.bbl causal_decision_making.pdf references.bib img
